// Posts
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
// Users
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';

// Widgets
export const GET_WIDGETS_SUCCESS = 'GET_WIDGETS_SUCCESS';
export const DELETE_WIDGET_SUCCESS = 'DELETE_WIDGET_SUCCESS';

// Search Layout
export const LOAD_SEARCH_LAYOUT = 'LOAD_SEARCH_LAYOUT';
